version: "3"

services:

  artifactory:
    build: ./artifactory-oss
    ports:
      - "8081:8081"
    volumes:
      - ./data:/var/opt/jfrog/artifactory
    container_name: artifactory
    restart: always
